[package]
name = "libsbml"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.27.1"
cxx = "1.0.140"
quick-xml = { version = "0.37.2", features = ["serialize"] }
serde = { version = "1.0.217", features = ["derive"] }


[build-dependencies]
autocxx-build = "0.27.1"
miette = { version = "5", features = ["fancy"] }
