[package]
name = "sbml"
version = "0.1.0"
edition = "2021"

[lib]
name = "sbml"
type = "staticlib"

[dependencies]
autocxx = "0.27.1"
cxx = "1.0.140"
quick-xml = { version = "0.37.2", features = ["serialize"] }
serde = { version = "1.0.217", features = ["derive"] }


[build-dependencies]
autocxx-build = "0.27.1"
cmake = "0.1.54"
miette = { version = "5", features = ["fancy"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
