name: Clippy check
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: '-Dwarnings'

jobs:
  clippy_check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: cargo install cargo-vcpkg

      - name: Build dependencies
        run: cargo vcpkg build

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
