name: Build and Test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-latest, windows-latest]
        include:
          - os: macos-14
            name: "macOS ARM"
          - os: macos-latest
            name: "macOS x86"
          - os: windows-latest
            name: "Windows"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test --verbose --all
