name: Build and Test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]
        include:
          - os: macos-14
            name: "macOS ARM"
          - os: macos-latest
            name: "macOS x86"
          - os: ubuntu-latest
            name: "Linux"
          - os: windows-latest
            name: "Windows"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install libxml2 on Windows
        if: matrix.os == 'windows-latest'
        run: |
          vcpkg install libxml2:x64-windows
          vcpkg integrate install

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
