name: Build and Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**/*.rs'
      - 'tests/**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10
  RUSTC_WRAPPER: sccache
  RUST_BACKTRACE: 1
  RUSTC_PARALLEL_COMPILER: true

jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-14
            name: 'macOS ARM'
          - os: macos-latest
            name: 'macOS x86'
          - os: windows-latest
            name: 'Windows'
          - os: ubuntu-latest
            name: 'Ubuntu'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libbz2-dev libexpat1-dev

      # Install and setup sccache
      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      # Setup Rust toolchain with caching
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      # Cache dependencies and build outputs
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
