name: Build and Test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]
        include:
          - os: macos-14
            name: "macOS ARM"
          - os: macos-latest
            name: "macOS x86"
          - os: ubuntu-latest
            name: "Linux"
          - os: windows-latest
            name: "Windows"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download pre-built Windows dependencies and SWIG
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          curl -L https://github.com/sbmlteam/libSBML-dependencies/releases/download/latest/libSBML-dependencies-1.0.1-x64-Release-static.zip > dependencies.zip
          unzip dependencies.zip
          mv libSBML-dependencies-1.0.1-x64-Release-static libsbml/dependencies

      - name: setup Windows environment
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          echo RUNTIME_LINKING_OPTION="-DWITH_STATIC_RUNTIME=ON" >> "${GITHUB_ENV}"
          echo PYTHON_LINKING_OPTION="-DWITH_PYTHON=ON" >> "${GITHUB_ENV}"

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
